# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissue < Formula
  desc ""
  homepage "https://github.com/hcgatewood/ghissue"
  version "0.1.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.8/ghissue_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "bd5952419979206f288747625d1e197dd786a7f9ab4d6c5415567ceebec11e53"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.8/ghissue_0.1.8_Linux_x86_64.tar.gz"
      sha256 "5c650d5b97246dae920fb34d360f2f5bc21a36c592decf39e0adc2e15f687f5d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.8/ghissue_0.1.8_Linux_arm64.tar.gz"
      sha256 "25d76cc8a6ddfcd75b19f778bba47d5c3c197e8cad55977ec96069adf0a0d649"
    end
  end

  def install
    bin.install "ghissue"
  end
end
