# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissue < Formula
  desc ""
  homepage "https://github.com/hcgatewood/ghissue"
  version "0.1.7"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.7/ghissue_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "3d167deae00360809ef01480106892f322047068852163bf663301303cf82bdf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.7/ghissue_0.1.7_Linux_x86_64.tar.gz"
      sha256 "d727b9f0953cea64a36cb86fe59f14a4108244a67f947e87e22572cf0809acc6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.7/ghissue_0.1.7_Linux_arm64.tar.gz"
      sha256 "883c7930f673563362cf7cdb06429d40f48f3dd8aefc323ce9fc46ca55b86a02"
    end
  end

  def install
    bin.install "ghissue"
  end
end
