# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissue < Formula
  desc ""
  homepage "https://github.com/hcgatewood/ghissue"
  version "0.1.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.4/ghissue_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "204cfc29bbc938ecc76976b99b80448fac7c7412dc8896e121940300424f61bb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.4/ghissue_0.1.4_Linux_x86_64.tar.gz"
      sha256 "174433bba5c5991101c80305315c60202e0699b76c209241f632885520661ea1"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.4/ghissue_0.1.4_Linux_arm64.tar.gz"
      sha256 "da309dea9ead96da25b099d217829def917752435ff8f31991055418c43232c4"
    end
  end

  def install
    bin.install "ghissue"
  end
end
